### ISSUE TITLE
2019-11-14 CEST_INT and CEST_EXT reporting problems for some partial AUCs

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#13]
### Issue

When asking for partial AUCs from _x_ to an extrapolated point, values for CEST_EXT are reported as the same value if they share _x_ in their partial AUC. Additionally there seems to be some IDs which cause some interpolated or extrapolated values to not be reported at all.

Hopefully the outputs below can help make sense of this issue. Understandably, there are a lot of different partial AUCs that I have not tested.

### Output 1

When running tc010 with additional partial AUCs from 0 to 120, 60 to 122, 60 to 144, 0 to 205 (where _x_ = 0 or 60) and 24 to 124 (24 being an existing point, 124 being extrapolated)  following output is given for `SDEID == 2925168`:

```
   PKDATAROWID   SDEID TIME  CEST_KEL  CEST_INT  CEST_EXT CEST_C0 CEST_TLAST
1           NA 2925168    7        NA 3.5950000        NA      NA         NA
2     22289754 2925168   24 1.7026376        NA        NA      NA         NA
3     22289755 2925168   48 0.5878072        NA        NA      NA         NA
4           NA 2925168   64        NA 0.3286667        NA      NA         NA
5     22289756 2925168   72 0.2029306        NA        NA      NA  0.2029306
6           NA 2925168  120        NA        NA 0.2837817      NA         NA
7           NA 2925168   60        NA 0.3905000        NA      NA         NA
8           NA 2925168  122        NA        NA 0.2050000      NA         NA
9           NA 2925168  144        NA        NA 0.2050000      NA         NA
10          NA 2925168  205        NA        NA 0.2837817      NA         NA
11          NA 2925168  124        NA        NA 0.2029306      NA         NA
```

As can be seen the value for CEST_EXT is the same for both 120 and 205 are the same, which shared the same lower value for their partial AUCs (_x_ = 0), while 122 and 144 are the same (_x_ = 60). 

This is not expected behaviour as it should be that the CEST_EXT value for each time point decreases and the time gets larger.

Additionally, it shows that CEST_TLAST at `TIME == 72` is lower than the CEST at `TIME == 120`. This may be intentional, but just raising it as a potential problem if it isn't intentional.

Despite this, the partial AUCs appear to be working correctly:

```
   AUC0_7  AUC8_48  AUC0_64 AUC0_120 AUC60_122 AUC60_144 AUC0_205 AUC24_124
8 19.0375 62.30995 91.99822 105.1922  13.87095  18.45428 125.7842  44.32238
```

### Output 2

For the same test case as above looking at `SDEID == 63536292` the following output is given:

```
   PKDATAROWID    SDEID TIME  CEST_KEL CEST_INT  CEST_EXT CEST_C0 CEST_TLAST
24          NA 63536292    7        NA  1.03375        NA      NA         NA
25    22289531 63536292   12 0.5189607       NA        NA      NA         NA
26          NA 63536292   64        NA  0.00000        NA      NA         NA
27          NA 63536292  120        NA       NA 0.2842993      NA         NA
28          NA 63536292   60        NA  0.00000        NA      NA         NA
29          NA 63536292  205        NA       NA 0.2842993      NA         NA
30    22289532 63536292   16 0.3693377       NA        NA      NA         NA
31    22289533 63536292   24 0.1870691       NA        NA      NA  0.1870691
```

In this output:

- interpolated values of 0 are given for 64 and 60
- extrapolated values for 120 and 205 are the same
- extrapolated values associated with an interpolated time point with value 0 are missing
- extrapolated value associated with an existing time point is missing

The associated value in `data_out` was:

```
     AUC0_7  AUC8_48  AUC0_64 AUC0_120 AUC60_122 AUC60_144 AUC0_205 AUC24_124
29 4.869875 9.248423 15.17517 21.99836         0         0 34.08108     2.292
```

The AUC from 60 to 122 and 60 to 144 may be very small, so this could be correct.

### Reproducible Example
```
#### Clean test environment ---------------------------------------------- ####
# Clean environment
rm(params, conc, vlist, results, results_list, r, e, mct, d, flags, p, klist, n, 
  ninc, nexc, k, rlist, dlist, nlist, slist, df, xmin, xmax, dk, flag_data, 
  est_data, outputdir)
 
profileid <- "SDEID"
args = commandArgs(trailingOnly=TRUE)
params = c()
 
#### Test Case 010 ------------------------------------------------------- ####
# M1 SD
# p <- "C:/Users/tensfeldt/Box Sync/EQuIP Computation Engine/Rudraya_executed_test_cases/tc010"
testcase.id <- "tc010"
p <- "testcase/tc010_M1SD"
params["INPUT1"] = file.path(p, "B1261002.in.csv")
params["parameterset"] ="PARAMETERLIST"
params["map"] = file.path(p, "tc010_mct_updated.csv")
params["flags"] = file.path(p, "B1261002_flag_data.in.csv")
params["OUTPUT"] ="."
print(params)
 
mct <- read_csv(params["map"])
write_file(toJSON(mct, na="string"), path=file.path(p, "tc010_mct_updated.json"))
params["map"] = file.path(p, "tc010_mct_updated.json")
 
flags <- read_csv(params["flags"])
write_file(toJSON(flags, na="string"), path=file.path(p, "tc010_flags.json"))
params["flags"] = file.path(p, "tc010_flags.json")
 
#### Read full concentration dataset ------------------------------------- ####
# Read conc
conc <- read.csv(file=params["INPUT1"], header=TRUE, sep=",", as.is=TRUE)
vlist <- c("PKDATAROWID", "PKPTMS", "PKCNCN", "PERIOD", "TREATXT")
 
# Read mct
mct <- params["map"]
###mct <- read_file(mct)
###mct <- gsub("[\\]+", "", mct)
mct <- fromJSON(mct)
 
# Read flags
flags <- params["flags"]
###flags <- read_file(flags)
###flags <- gsub("[\\]+", "", flags)
flags <- fromJSON(flags)
 
# ParameterSet
if(is.na(params["parameterset"])) { params["parameterset"] <- "PARAMETERDISPLAYLIST" }
parameterset <- params["parameterset"]
 
# FLAGS is a subset for the specific profile, subset concentration dataframe 
#  to those records by PKDATAROWID
d <- conc[is.element(conc$PKDATAROWID, flags$PKDATAROWID),]
 
# Add in missing required parameters for virtual compute call
klist <- c("KEL", "KELRSQ", "KELNOPT", "THALFF")
if(!is.element("PARAMETERDISPLAYLIST", names(mct))) { mct$PARAMETERDISPLAYLIST <- "" }
for(i in klist) {
  ###if(regexpr(i, mct$PARAMETERDISPLAYLIST, ignore.case=TRUE)==-1) { mct$PARAMETERDISPLAYLIST <- c(mct$PARAMETERDISPLAYLIST, i) }
  if(regexpr(i, mct$PARAMETERDISPLAYLIST, ignore.case=TRUE)==-1) { mct$PARAMETERDISPLAYLIST <- paste(mct$PARAMETERDISPLAYLIST, i, sep=";") }
}
 
# Remove any leading semi-colons ";"
mct$PARAMETERDISPLAYLIST <- gsub("^;*", "", mct$PARAMETERDISPLAYLIST, ignore.case=TRUE, perl=TRUE)
 
# For virtual compute call only: Subset the parameters to be calculated to those in parameterdisplaylist
if(!is.element("PARAMETERLIST", names(mct))) { mct$PARAMETERLIST <- "" }
 
# Check whether TIME selection has been set in MCT - default to NOMINAL
if(!is.element("TIME", names(mct))) { mct$TIME <- "NOMINAL" }
 
# Determine whether there are any points selected for inclusion in the terminal elimination phase via 
#  FLGEXKEL (0=not excluded/included; 1=excluded/not included)
#  ***What happens if there are no flags provided?***
n <- factor(flags$FLGEXKEL, levels=c(0,1))
ninc <- length(n[n==0])
nexc <- length(n[n==1])
#### Final changes to test ----------------------------------------------- ####
### Add partial AUC
mct$AUC.4.T1 <- 0
mct$AUC.4.T2 <- 120
mct$AUC.5.T1 <- 60
mct$AUC.5.T2 <- 122
mct$AUC.6.T1 <- 60
mct$AUC.6.T2 <- 144
mct$AUC.7.T1 <- 0
mct$AUC.7.T2 <- 205
mct$AUC.8.T1 <- 24
mct$AUC.8.T2 <- 124

#### Run computation engine ---------------------------------------------- ####
### Run computation
results_list <- run_computation(data = d, map = mct, flag = flags, 
  parameterset = parameterset)

### Save results to objects
r <- results_list$data_out
e <- results_list$est_data
f <- results_list$flag_data

### View output
e[e$SDEID == 2925168, ]
r[r$SDEID == 2925168, c("AUC0_7", "AUC8_48", "AUC0_64", "AUC0_120", "AUC60_122", "AUC60_144", "AUC0_205", "AUC24_124")]
e[e$SDEID == 63536292, ]
r[r$SDEID == 63536292, c("AUC0_7", "AUC8_48", "AUC0_64", "AUC0_120", "AUC60_122", "AUC60_144", "AUC0_205", "AUC24_124")]
```

**Comment by jhhughes256** [comment]
### Update

This issue was first seen in 6284702d62. As of b2bf9b3f3c the output has changed but it appears that there are still some underlying issues.

### Output 1

This no longer uses the same extrapolated values for two different times if they shared an initial time in their partial AUC (e.g. 60-122, 60-144). However the extrapolated values in `est_data` still do not completely make sense, with values increasing and decreasing over time.

```
   PKDATAROWID   SDEID TIME  CEST_KEL  CEST_INT    CEST_EXT CEST_C0 CEST_TLAST
4           NA 2925168    7        NA 3.5950000          NA      NA         NA
1     22289754 2925168   24 1.7026376        NA          NA      NA         NA
2     22289755 2925168   48 0.5878072        NA          NA      NA         NA
7           NA 2925168   60        NA 0.3905000          NA      NA         NA
5           NA 2925168   64        NA 0.3286667          NA      NA         NA
3     22289756 2925168   72 0.2029306        NA          NA      NA  0.2029306
6           NA 2925168  120        NA        NA 0.067074515      NA         NA
8           NA 2925168  122        NA        NA 0.013984296      NA         NA
11          NA 2925168  124        NA        NA 0.020257779      NA         NA
9           NA 2925168  144        NA        NA 0.004290924      NA         NA
10          NA 2925168  205        NA        NA 0.005215069      NA         NA
```

The `data_out` output still appears correct, though it has changed from the previous output implying the previous output was not correct.

```
   AUC0_7  AUC8_48  AUC0_64 AUC0_120 AUC60_122 AUC60_144 AUC0_205 AUC24_124
8 19.0375 62.30995 91.99822 99.48956   7.01127  7.191775  100.801  37.86694
```

### Output 2

This issue remains unchanged for `est_data`.

```
   PKDATAROWID    SDEID TIME  CEST_KEL CEST_INT   CEST_EXT CEST_C0 CEST_TLAST
42          NA 63536292    7        NA  1.03375         NA      NA         NA
14    22289531 63536292   12 0.5189607       NA         NA      NA         NA
22    22289532 63536292   16 0.3693377       NA         NA      NA         NA
32    22289533 63536292   24 0.1870691       NA         NA      NA  0.1870691
72          NA 63536292   60        NA  0.00000         NA      NA         NA
52          NA 63536292   64        NA  0.00000         NA      NA         NA
62          NA 63536292  120        NA       NA 0.01543093      NA         NA
82          NA 63536292  205        NA       NA 0.00116950      NA         NA
```

However, `data_out` no longer appears correct as `AUC0_205` is less than `AUC 0_120`. This may be related to what is causing the `CEST_INT` output of zero.

```
     AUC0_7  AUC8_48  AUC0_64 AUC0_120 AUC60_122 AUC60_144 AUC0_205 AUC24_124
29 4.869875 9.248423 15.17517 15.54552         0         0 15.25295     2.292
```

**Comment by jhhughes256** [comment]
### Update

#### Output 1

It appears that the values for CEST_EXT do not decrease in a descending order as an extrapolation from an interpolated point may run parallel to an extrapolation from zero (not contain the same values). Therefore this behaviour is expected. It may be worth having a discussion if this is desired. 

This may also be the reason behind receiving multiple different CEST_EXT values for the same time point in `est_data` when asking for a partial AUC from two different interpolated values to the same extrapolated value. This behaviour is shown below. Again, this behaviour may not be a problem from a usability perspective.

```
    PKDATAROWID     SDEID TIME     CEST_KEL     CEST_INT     CEST_EXT CEST_C0 CEST_TLAST
4            NA   2925168    7           NA   3.59500000           NA      NA         NA
9            NA   2925168   20           NA   1.97000000           NA      NA         NA
1      22289754   2925168   24   1.70263761           NA           NA      NA         NA
6            NA   2925168   30           NA   1.43400000           NA      NA         NA
2      22289755   2925168   48   0.58780724           NA           NA      NA         NA
5            NA   2925168   64           NA   0.32866667           NA      NA         NA
3      22289756   2925168   72   0.20293065           NA           NA      NA 0.20293065
8            NA   2925168  124           NA           NA 1.820280e-02      NA         NA
7            NA   2925168  144           NA           NA 7.234184e-03      NA         NA
10           NA   2925168  144           NA           NA 8.614477e-03      NA         NA
51           NA  40876220    7           NA   1.11575000           NA      NA         NA
12     22289571  40876220   16   0.49544432           NA           NA      NA         NA
101          NA  40876220   20           NA   0.45800000           NA      NA         NA
21     22289572  40876220   24   0.36517471           NA           NA      NA         NA
71           NA  40876220   30           NA   0.31600000           NA      NA         NA
31     22289573  40876220   48   0.14622386           NA           NA      NA         NA
61           NA  40876220   64           NA   0.08246667           NA      NA         NA
41     22289574  40876220   72   0.05855120           NA           NA      NA 0.05855120
91           NA  40876220  124           NA           NA 9.438341e-03      NA         NA
81           NA  40876220  144           NA           NA 4.609479e-03      NA         NA
11           NA  40876220  144           NA           NA 3.812556e-03      NA         NA
```

```
      SDEID     AUC0_7    AUC8_48     AUC0_64   AUC30_124   AUC30_144   AUC20_144
1 111299859    5.15075   16.11586    23.59851    4.524045    4.512813    7.948354
2 112146587   16.63043   27.18657    47.51955    5.069071    5.068484   10.398530
3 123811839 1826.88593 1140.50993  3155.39210  270.952202  273.476887  484.930970
4 145593586  759.77223 1482.00641  2543.66350  855.761009  862.754338 1243.106279
5 202367199 6447.26053 5524.24397 12915.26200 1628.969960 1645.235279 2758.031814
6 233891605 2026.37365 1432.19220  3683.11590  367.912701  370.179797  642.776481
```

#### Output 2

I've noticed that this occurs due to the two final concentrations in the dataset being zero.

```
      SDEID CONC11 CONC12 CONC13 CONCTIME11 CONCTIME12 CONCTIME13
29 63536292  0.191      0      0         24         48         72
```

Therefore the value for CEST_INT is zero as it is interpolating between two zero values. I think it should be discussed if this is desired behaviour and/or whether it is likely to be an issue for users.

**Comment by jhhughes256** [comment]
### Update

As of 92ca12aa14 the problem outlined in **Output 1** can no longer be replicated. **Output 2** can still be replicated.

**Comment by tensfeldt** [comment]
Not retested with commit 96f6417 since no indicate that it has been addressed. #13 Remains an open issue. Set to priority label.

**Comment by rudraya** [comment]
This issue was addressed in 6aba420, please let me know if it still occurs.

**Comment by jhhughes256** [comment]
### Update

This issue appears to be mostly fixed as of 6aba420. It should be mentioned that the latest results for **Output 2** appear as shown below:

```
    PKDATAROWID    SDEID TIME  CEST_KEL CEST_INT     CEST_EXT CEST_C0 CEST_TLAST
42           NA 63536292    7        NA  1.03375           NA      NA         NA
14     22289531 63536292   12 0.5189607       NA           NA      NA         NA
22     22289532 63536292   16 0.3693377       NA           NA      NA         NA
32     22289533 63536292   24 0.1870691       NA           NA      NA  0.1870691
72           NA 63536292   60        NA       NA 4.498695e-05      NA         NA
92           NA 63536292   60        NA       NA 6.929101e-06      NA         NA
52           NA 63536292   64        NA       NA 6.235821e-03      NA         NA
62           NA 63536292  120        NA       NA 5.332636e-05      NA         NA
82           NA 63536292  122        NA       NA 4.498695e-05      NA         NA
121          NA 63536292  124        NA       NA 3.795169e-05      NA         NA
102          NA 63536292  144        NA       NA 6.929101e-06      NA         NA
112          NA 63536292  205        NA       NA 3.873349e-08      NA         NA
```

The values that were once interpolated, despite being beyond the final time point, are now treated as extrapolated values. These new extrapolated values have the same issue as seen in **Output 1** where values are not steadily decreasing as time increases, and multiple extrapolated values are provided for the same time.

**Comment by rudraya** [comment]
This issue was addressed in 18821dc, please let me know if it still occurs.

**Comment by jhhughes256** [comment]
### Update

This issue no longer occurs as of 18821dc. Final output for **Output 2** shown below:

```
    PKDATAROWID    SDEID TIME  CEST_KEL CEST_INT     CEST_EXT CEST_C0 CEST_TLAST
14           NA 63536292    7        NA  1.03375           NA      NA         NA
22     22289531 63536292   12 0.5189607       NA           NA      NA         NA
32     22289532 63536292   16 0.3693377       NA           NA      NA         NA
42     22289533 63536292   24 0.1870691       NA           NA      NA  0.1870691
72           NA 63536292   60        NA       NA 8.762024e-03      NA         NA
52           NA 63536292   64        NA       NA 6.235821e-03      NA         NA
62           NA 63536292  120        NA       NA 5.332636e-05      NA         NA
82           NA 63536292  122        NA       NA 4.498695e-05      NA         NA
112          NA 63536292  124        NA       NA 3.795169e-05      NA         NA
92           NA 63536292  144        NA       NA 6.929101e-06      NA         NA
102          NA 63536292  205        NA       NA 3.873349e-08      NA         NA
```

**Comment by tensfeldt** [comment]
As of commit 18821dc this issue remains. While first specific issue reported has been corrected with output 1, the are remaining problems with output2.

## output 1: SDEID==2925168  
```
> e[e$SDEID==2925168,]
  PKDATAROWID   SDEID TIME  CEST_KEL CEST_INT     CEST_EXT CEST_C0 CEST_TLAST
1    22289754 2925168   24 1.7026376       NA           NA      NA         NA
2    22289755 2925168   48 0.5878072       NA           NA      NA         NA
5          NA 2925168   60        NA   0.3905           NA      NA         NA
3    22289756 2925168   72 0.2029306       NA           NA      NA  0.2029306
4          NA 2925168  120        NA       NA 0.0241865014      NA         NA
6          NA 2925168  122        NA       NA 0.0221351487      NA         NA
7          NA 2925168  144        NA       NA 0.0083499862      NA         NA
8          NA 2925168  205        NA       NA 0.0005593997      NA         NA
```

## output 2: SDEID==63536292
Here we can see that the value at 60 is reported as extrapolated but it needs to be interpolated since there are observed points at 48 and 72 hours. Since the concentration for those 2 observed points are zero concentration it is expected that the interpolated value for 60 hours will be zero concentration.

The extrapolated points at 120,122,144 and 205 hours appear reasonable but point out that we're estimating concentrations below the level of quantification ("<0.05" for profile 63536292) and appear to be larger than the value interpolated for 60 hours which will provide results that appear inconcsistent.

We might have to come up with a rule that identifies extrapolated values below the level of quantification as zero but for now we can accept the current behavior and might refine it later. 

```
> e[e$SDEID==63536292,]
   PKDATAROWID    SDEID TIME  CEST_KEL CEST_INT     CEST_EXT CEST_C0 CEST_TLAST
12    22289531 63536292   12 0.5189607       NA           NA      NA         NA
22    22289532 63536292   16 0.3693377       NA           NA      NA         NA
32    22289533 63536292   24 0.1870691       NA           NA      NA  0.1870691
52          NA 63536292   60        NA       NA 8.762024e-03      NA         NA
42          NA 63536292  120        NA       NA 5.332636e-05      NA         NA
62          NA 63536292  122        NA       NA 4.498695e-05      NA         NA
72          NA 63536292  144        NA       NA 6.929101e-06      NA         NA
82          NA 63536292  205        NA       NA 3.873349e-08      NA         NA
> d[d$SDEID==63536292, c("SDEID", "PKPTMS", "PKCNCN", "PKCNC")]
      SDEID PKPTMS PKCNCN   PKCNC
53 63536292    0.0  0.000 <0.0500
54 63536292    0.5  0.469   0.469
55 63536292    1.0  0.524   0.524
56 63536292    1.5  0.419   0.419
57 63536292    2.0  0.405   0.405
58 63536292    2.5  0.397   0.397
59 63536292    4.0  0.895   0.895
60 63536292    8.0  1.080    1.08
61 63536292   12.0  0.541   0.541
62 63536292   16.0  0.347   0.347
63 63536292   24.0  0.191   0.191
64 63536292   48.0  0.000 <0.0500
65 63536292   72.0  0.000 <0.0500
```

**Comment by tensfeldt** [comment]
I don't think that Jim considered output 2 in his decision to close this issue. It remains open.

**Comment by tensfeldt** [comment]
The rationale to retain this as an open issue has been reconsidered. The particular case illustrated by Output 2 above is a common case. Since 60 hours is not in the original sampling design, i.e. not one of the observed data points a decision must be made as to whether it is interpolated from other observed data points (48 hours and 78 hours both < the lower limit of quantification so imputed as zero) or extrapolated from data selected for the terminal elimination phase. The current algorithm doesn't take into account data points <LLOQ/BLQ following the terminal elimination phase since these are imputed as zero and thus elects to estimate the concentration via extrapolation. 

At this time, this behavior will be adopted rather than forcing imputation between 2 observed data points at zero concentration. This issue is thus considered closed at this time.
